---
apiVersion: api.tsb.tetrate.io/v2
kind: Tenant
metadata:
  organization: tetrate
  name: commercialbank
spec:
  description: Tenant for Commercial Bank Business Unit
  displayName: CommercialBank
