---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: retailbank
  workspace: retail2
  name: retail2-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-retail2
        labels:
          app: eastwest-gw-retail2
      exposedServices:
      - serviceLabels:
          app: front-retail2
          service: front-retail2
      - serviceLabels:
          app: mid-retail2
          service: mid-retail2
      - serviceLabels:
          app: back-retail2
          service: back-retail2
  defaultTrafficSetting:
    reachability:
      hosts:
      - gateway-retail2/*
      - front-retail2/*
      - mid-retail2/*
      - back-retail2/*
      mode: CUSTOM