---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: retailbank
  workspace: retail1
  name: retail1-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-retail1
        labels:
          app: eastwest-gw-retail1
      exposedServices:
      - serviceLabels:
          app: front-retail1
          service: front-retail1
      - serviceLabels:
          app: mid-retail1
          service: mid-retail1
      - serviceLabels:
          app: back-retail1
          service: back-retail1
  defaultTrafficSetting:
    reachability:
      hosts:
      - gateway-retail1/*
      - front-retail1/*
      - mid-retail1/*
      - back-retail1/*
      mode: CUSTOM