---
private1-workspace:
  needs:
    - privatebank-tenant
  stage: post-trigger
  trigger:
    project: applications/cashmgmt/private1/tsb-workspace-admin
private2-workspace:
  needs:
    - privatebank-tenant
  stage: post-trigger
  trigger:
    project: applications/cashmgmt/private2/tsb-workspace-admin
k8s-deploy:
  artifacts:
    paths:
      - output
  needs:
    - prereq
  script:
    - ./k8s.sh deploy
  stage: k8s-deploy
prereq:
  allow_failure: false
  artifacts:
    paths:
      - output
  cache:
    key: output
    paths:
      - output
  script:
    - ./prereq.sh check
  stage: prereq
  timeout: 30m
stages:
  - prereq
  - k8s-deploy
  - tsb-deploy
  - post-trigger
privatebank-tenant:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
    url: https://tctl.demo.tetrate.io
  needs:
    - prereq
    - k8s-deploy
  resource_group: tctl
  script:
    - ./tsb.sh deploy
  stage: tsb-deploy
  tags:
    - application-tctl
variables:
  TERM: xterm