---
apiVersion: api.tsb.tetrate.io/v2
kind: Team
metadata:
  organization: tetrate
  name: everyone
spec:
  members:
  - organizations/tetrate/users/tsb-platform-mngr

  - organizations/tetrate/users/cashmgmt-mngr
  - organizations/tetrate/users/commercialbank-mngr
  - organizations/tetrate/users/investmentbank-mngr
  - organizations/tetrate/users/privatebank-mngr
  - organizations/tetrate/users/retailbank-mngr
  - organizations/tetrate/users/wealthmgmt-mngr

  - organizations/tetrate/users/cash1-tl
  - organizations/tetrate/users/cash2-tl
  - organizations/tetrate/users/comm1-tl
  - organizations/tetrate/users/comm2-tl
  - organizations/tetrate/users/invest1-tl
  - organizations/tetrate/users/invest2-tl
  - organizations/tetrate/users/private1-tl
  - organizations/tetrate/users/private2-tl
  - organizations/tetrate/users/retail1-tl
  - organizations/tetrate/users/retail2-tl
  - organizations/tetrate/users/wealth1-tl
  - organizations/tetrate/users/wealth2-tl

  - organizations/tetrate/users/dev-cash1
  - organizations/tetrate/users/dev-cash1-frontend
  - organizations/tetrate/users/dev-cash1-middleware
  - organizations/tetrate/users/dev-cash1-backend
  - organizations/tetrate/users/dev-cash2
  - organizations/tetrate/users/dev-cash2-frontend
  - organizations/tetrate/users/dev-cash2-middleware
  - organizations/tetrate/users/dev-cash2-backend

  - organizations/tetrate/users/dev-comm1
  - organizations/tetrate/users/dev-comm1-frontend
  - organizations/tetrate/users/dev-comm1-middleware
  - organizations/tetrate/users/dev-comm1-backend
  - organizations/tetrate/users/dev-comm2
  - organizations/tetrate/users/dev-comm2-frontend
  - organizations/tetrate/users/dev-comm2-middleware
  - organizations/tetrate/users/dev-comm2-backend

  - organizations/tetrate/users/dev-invest1
  - organizations/tetrate/users/dev-invest1-frontend
  - organizations/tetrate/users/dev-invest1-middleware
  - organizations/tetrate/users/dev-invest1-backend
  - organizations/tetrate/users/dev-invest2
  - organizations/tetrate/users/dev-invest2-frontend
  - organizations/tetrate/users/dev-invest2-middleware
  - organizations/tetrate/users/dev-invest2-backend

  - organizations/tetrate/users/dev-private1
  - organizations/tetrate/users/dev-private1-frontend
  - organizations/tetrate/users/dev-private1-middleware
  - organizations/tetrate/users/dev-private1-backend
  - organizations/tetrate/users/dev-private2
  - organizations/tetrate/users/dev-private2-frontend
  - organizations/tetrate/users/dev-private2-middleware
  - organizations/tetrate/users/dev-private2-backend

  - organizations/tetrate/users/dev-retail1
  - organizations/tetrate/users/dev-retail1-frontend
  - organizations/tetrate/users/dev-retail1-middleware
  - organizations/tetrate/users/dev-retail1-backend
  - organizations/tetrate/users/dev-retail2
  - organizations/tetrate/users/dev-retail2-frontend
  - organizations/tetrate/users/dev-retail2-middleware
  - organizations/tetrate/users/dev-retail2-backend

  - organizations/tetrate/users/dev-wealth1
  - organizations/tetrate/users/dev-wealth1-frontend
  - organizations/tetrate/users/dev-wealth1-middleware
  - organizations/tetrate/users/dev-wealth1-backend
  - organizations/tetrate/users/dev-wealth2
  - organizations/tetrate/users/dev-wealth2-frontend
  - organizations/tetrate/users/dev-wealth2-middleware
  - organizations/tetrate/users/dev-wealth2-backend
