---
apiVersion: api.tsb.tetrate.io/v2
kind: Team
metadata:
  organization: tetrate
  name: investmentbank
spec:
  members:
  - organizations/tetrate/users/mngr-investmentbank
  - organizations/tetrate/users/tl-invest1
  - organizations/tetrate/users/tl-invest2
  - organizations/tetrate/users/dev-invest1
  - organizations/tetrate/users/dev-invest2
  - organizations/tetrate/users/dev-invest1-frontend
  - organizations/tetrate/users/dev-invest2-frontend
  - organizations/tetrate/users/dev-invest1-middleware
  - organizations/tetrate/users/dev-invest2-middleware
  - organizations/tetrate/users/dev-invest1-backend
  - organizations/tetrate/users/dev-invest2-backend
