---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: investmentbank
  workspace: invest2
  name: invest2
spec:
  description: Traffic Group for Application Invest2
  displayName: Invest2
  namespaceSelector:
    names:
      - "*/front-invest2"
      - "*/mid-invest2"
      - "*/back-invest2"
  configMode: BRIDGED
