---
prereq:
  allow_failure: false
  script:
    - ./prereq.sh check
  stage: prereq
  timeout: 15m
stages:
  - prereq
  - tsb-deploy
tsb-deploy:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
  resource_group: tctl
  script:
    - ./tsb.sh deploy
  stage: tsb-deploy
variables:
  TERM: xterm