---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: cashmgmt
    tsb-workspace: cash1
  labels:
    istio-injection: enabled
  name: ns-cash1a
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: cashmgmt
    tsb-workspace: cash1
  labels:
    istio-injection: enabled
  name: ns-cash1b
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: cashmgmt
    tsb-workspace: cash1
  labels:
    istio-injection: enabled
  name: ns-cash1c
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: cashmgmt
    tsb-workspace: cash1
  name: gateway-cash1
