---
k8s-gateways:
  artifacts:
    paths:
      - output
  needs:
    - prereq
  script:
    - ./k8s.sh config-gateways
  stage: k8s-gateways
prereq:
  allow_failure: false
  script:
    - ./prereq.sh check
  stage: prereq
  timeout: 15m
stages:
  - prereq
  - k8s-gateways
  - tsb-groups
  - tsb-groupsettings
  - tsb-teams
  - tsb-serviceaccounts
  - tsb-accessbindings
tsb-accessbindings:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
    - tsb-groups
    - tsb-teams
    - tsb-serviceaccounts
  resource_group: tctl
  script:
    - ./tsb.sh config-accessbindings
  stage: tsb-accessbindings
tsb-groups:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
  resource_group: tctl
  script:
    - ./tsb.sh config-groups
  stage: tsb-groups
tsb-groupsettings:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
    - tsb-groups
  resource_group: tctl
  script:
    - ./tsb.sh config-groupsettings
  stage: tsb-groupsettings
tsb-serviceaccounts:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
    - tsb-groups
  resource_group: tctl
  script:
    - ./tsb.sh config-serviceaccounts
  stage: tsb-serviceaccounts
tsb-teams:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
  resource_group: tctl
  script:
    - ./tsb.sh config-teams
  stage: tsb-teams
variables:
  TERM: xterm