---
k8s-gateways:
  artifacts:
    paths:
      - output
  needs:
    - prereq
  script:
    - ./k8s.sh config-gateways
  stage: k8s-gateways
prereq:
  allow_failure: false
  script:
    - ./prereq.sh check
  stage: prereq
  timeout: 15m
stages:
  - prereq
  - k8s-gateways
  - tsb-workspaces
  - tsb-workspacesettings
  - tsb-teams
  - tsb-serviceaccounts
  - tsb-accessbindings
tsb-accessbindings:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
    - tsb-workspaces
    - tsb-teams
    - tsb-serviceaccounts
  resource_group: tctl
  script:
    - ./tsb.sh config-accessbindings
  stage: tsb-accessbindings
tsb-serviceaccounts:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
    - tsb-workspaces
  resource_group: tctl
  script:
    - ./tsb.sh config-serviceaccounts
  stage: tsb-serviceaccounts
tsb-teams:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
  resource_group: tctl
  script:
    - ./tsb.sh config-teams
  stage: tsb-teams
tsb-workspaces:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
    - k8s-namespaces
  resource_group: tctl
  script:
    - ./tsb.sh config-workspaces
  stage: tsb-workspaces
tsb-workspacesettings:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
    - tsb-workspaces
  resource_group: tctl
  script:
    - ./tsb.sh config-workspacesettings
  stage: tsb-workspacesettings
variables:
  TERM: xterm