---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: investmentbank
  workspace: invest1
  name: invest1
spec:
  description: Traffic Group for Application Invest1
  displayName: Invest1
  namespaceSelector:
    names:
      - "*/front-invest1"
      - "*/mid-invest1"
      - "*/back-invest1"
  configMode: BRIDGED
