---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  group: ingress-private1
  name: ingress-gw-private1
spec:
  description: Ingress Gateway for Application Private1
  displayName: IngressGwPrivate1
  workloadSelector:
    namespace: gateway-private1
    labels:
      app: ingress-gw-private1
  http:
  - name: uvw
    hostname: private1.demo.tetrate.io
    port: 443
    tls:
      mode: SIMPLE
      secretName: private1-cert
    routing:
      rules:
      - route:
          host: front-private1/front-private1.front-private1.svc.cluster.local
          port: 80
