---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  group: ingress-private1
  name: tier1-to-ingress
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private1/securitygroups/tier1-private1
         to:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private1/securitygroups/ingress-private1
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  group: front-private1
  name: ingress-to-front
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private1/securitygroups/ingress-private1
         to:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private1/securitygroups/front-private1
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  group: mid-private1
  name: front-to-mid
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private1/securitygroups/front-private1
         to:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private1/securitygroups/mid-private1
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  group: back-private1
  name: mid-to-back
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private1/securitygroups/mid-private1
         to:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private1/securitygroups/back-private1
