---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  group: tier1-private1
  name: tier1-gw-private1
spec:
  description: Tier1 Gateway Group for Application Private1
  displayName: Tier1GwPrivate1
  workloadSelector:
    namespace: tier1-gw-private1
    labels:
      app: tier1-gw-private1
  externalServers:
  - name: private1-mtls
    hostname: private1.demo.tetrate.io
    port: 443
    tls:
      mode: MUTUAL
      secretName: private1-cert
    clusters:
    - name: active
    - name: standby
