---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: front-private1vw
  group: tier1-private1
  name: tier1-gw-private1
spec:
  description: Tier1 Gateway Group for Application Private1
  displayName: Tier1GwPrivate1
  workloadSelector:
    namespace: tier1-gw-private1
    labels:
      app: tier1-gw-private1
  externalServers:
  - name: uvw-mtls
    hostname: uvw.demo.tetrate.io
    port: 443
    tls:
      mode: MUTUAL
      secretName: front-private1vw-cert
    clusters:
    - name: active
    - name: standby
