---
apiVersion: api.tsb.tetrate.io/v2
kind: ServiceAccount
metadata:
  name: cicd-prod-abc
  organization: tetrate
spec:
  displayName: CICD_PROD_ABC ServiceAccount
  description: ServiceAccount used for GitLab CICD deployment of ABC in Production
