---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: app-private2
  name: app-private2-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-private2
        labels:
          app: eastwest-gw-private2
      exposedServices:
      - serviceLabels:
          app: app-private2a
          service: app-private2a
      - serviceLabels:
          app: app-private2b
          service: app-private2b
      - serviceLabels:
          app: app-private2c
          service: app-private2c
  defaultTrafficSetting:
    reachability:
      hosts:
      - gateway-private2/*
      - ns-private2a/*
      - ns-private2b/*
      - ns-private2c/*
      mode: CUSTOM