---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  name: private1-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-private1
        labels:
          app: eastwest-gw-private1
      exposedServices:
      - serviceLabels:
          app: front-private1
          service: front-private1
      - serviceLabels:
          app: mid-private1
          service: mid-private1
      - serviceLabels:
          app: back-private1
          service: back-private1
  defaultTrafficSetting:
    reachability:
      hosts:
      - gateway-private1/*
      - front-private1/*
      - mid-private1/*
      - back-private1/*
      mode: CUSTOM