---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private2
  name: private2-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-private2
        labels:
          app: eastwest-gw-private2
      exposedServices:
      - serviceLabels:
          app: front-private2
          service: front-private2
      - serviceLabels:
          app: mid-private2
          service: mid-private2
      - serviceLabels:
          app: back-private2
          service: back-private2
  defaultTrafficSetting:
    reachability:
      hosts:
      - gateway-private2/*
      - front-private2/*
      - mid-private2/*
      - back-private2/*
      mode: CUSTOM