---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  name: private1-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-private1
        labels:
          app: eastwest-gw-private1
      exposedServices:
      - serviceLabels:
          app: frontend-private1
          service: frontend-private1
      - serviceLabels:
          app: middleware-private1
          service: middleware-private1
      - serviceLabels:
          app: backend-private1
          service: backend-private1
  defaultTrafficSetting:
    reachability:
      hosts:
      - gateway-private1/*
      - frontend-private1/*
      - middleware-private1/*
      - backend-private1/*
      mode: CUSTOM