---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  name: tier1-private1
spec:
  description: Tier1 Gateway Group for Application Private1
  displayName: Tier1Private1
  namespaceSelector:
    names:
      - "mgmt/tier1-gw-private1"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  name: ingress-private1
spec:
  description: Ingress Gateway Group for Application Private1
  displayName: IngressPrivate1
  namespaceSelector:
    names:
      - "*/gateway-private1"
  configMode: BRIDGED
