---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: front-private1vw
  name: gwgroup-tier1-uvw
spec:
  description: Tier1 Gateway Group for Application UVW
  displayName: Tier1UVW
  namespaceSelector:
    names:
      - "mgmt/tier1-gw-uvw"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: front-private1vw
  name: gwgroup-ingress-uvw
spec:
  description: Ingress Gateway Group for Application UVW
  displayName: IngressUVW
  namespaceSelector:
    names:
      - "*/gateway-uvw"
  configMode: BRIDGED
