---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  name: tier1-private1
spec:
  description: Security Group for Tier1Gateway Private1
  displayName: Tier1Private1
  namespaceSelector:
    names:
      - "mgmt/tier1-gw-private1"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  name: ingress-private1
spec:
  description: Security Group for IngressGateway Private1
  displayName: IngressPrivate1
  namespaceSelector:
    names:
      - "*/gateway-private1"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  name: front-private1
spec:
  description: Security Group for Frontend of Private1 Application
  displayName: FrontPrivate1
  namespaceSelector:
    names:
      - "*/front-private1"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  name: mid-private1
spec:
  description: Security Group for Middleware of Private1 Application
  displayName: MidPrivate1
  namespaceSelector:
    names:
      - "*/mid-private1"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  name: back-private1
spec:
  description: Security Group for Backend of Private1 Application
  displayName: BackPrivate1
  namespaceSelector:
    names:
      - "*/back-private1"
  configMode: BRIDGED
