---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private1
  name: private1
spec:
  description: Traffic Group for Application Private1
  displayName: Private1
  namespaceSelector:
    names:
      - "*/front-private1"
      - "*/mid-private1"
      - "*/back-private1"
  configMode: BRIDGED
