---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: privatebank
    tsb-workspace: private2
  labels:
    istio-injection: enabled
  name: ns-private2a
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: privatebank
    tsb-workspace: private2
  labels:
    istio-injection: enabled
  name: ns-private2b
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: privatebank
    tsb-workspace: private2
  labels:
    istio-injection: enabled
  name: ns-private2c
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: privatebank
    tsb-workspace: private2
  name: gateway-private2
