---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/privatebank/workspaces/private1
  labels:
    istio-injection: enabled
  name: front-private1
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/privatebank/workspaces/private1
  labels:
    istio-injection: enabled
  name: mid-private1
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/privatebank/workspaces/private1
  labels:
    istio-injection: enabled
  name: back-private1
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/privatebank/workspaces/private1
  name: gateway-private1
