---
apiVersion: rbac.tsb.tetrate.io/v2
kind: AccessBindings
metadata:
  fqn: organizations/tetrate/tenants/commercialbank
spec:
  allow:
  - role: rbac/admin
    subjects:
    - serviceAccount: organizations/tetrate/serviceaccounts/commercialbank
    - user: organizations/tetrate/users/mngr-pubbank
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: AccessBindings
metadata:
  fqn: organizations/tetrate/tenants/privatebank
spec:
  allow:
  - role: rbac/admin
    subjects:
    - serviceAccount: organizations/tetrate/serviceaccounts/privatebank
    - user: organizations/tetrate/users/mngr-privbank
