---
apiVersion: rbac.tsb.tetrate.io/v2
kind: AccessBindings
metadata:
  fqn: organizations/tetrate/tenants/privatebank
spec:
  allow:
  - role: rbac/admin
    subjects:
    - serviceAccount: organizations/tetrate/serviceaccounts/privatebank
    - user: organizations/tetrate/users/mngr-privatebank
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: AccessBindings
metadata:
  fqn: organizations/tetrate/tenants/retailbank
spec:
  allow:
  - role: rbac/admin
    subjects:
    - serviceAccount: organizations/tetrate/serviceaccounts/retailbank
    - user: organizations/tetrate/users/mngr-retailbank
