---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: wealthmgmt
  workspace: wealth2
  name: wealth2-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-wealth2
        labels:
          app: eastwest-gw-wealth2
      exposedServices:
      - serviceLabels:
          app: front-wealth2
          service: front-wealth2
      - serviceLabels:
          app: mid-wealth2
          service: mid-wealth2
      - serviceLabels:
          app: back-wealth2
          service: back-wealth2
  defaultTrafficSetting:
    reachability:
      hosts:
      - gateway-wealth2/*
      - front-wealth2/*
      - mid-wealth2/*
      - back-wealth2/*
      mode: CUSTOM