---
apiVersion: v1
kind: Service
metadata:
  name: app-z
  namespace: ns-z
  labels:
    app: app-z
    service: app-z
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 3000
      targetPort: 3000
      name: tcp
  selector:
    app: app-z
