---
apiVersion: api.tsb.tetrate.io/v2
kind: Team
metadata:
  organization: tetrate
  name: everyone
spec:
  members:
  - organizations/tetrate/users/dev-a
  - organizations/tetrate/users/dev-b
  - organizations/tetrate/users/dev-c
  - organizations/tetrate/users/mngr-abc
  - organizations/tetrate/users/dev-d
  - organizations/tetrate/users/dev-e
  - organizations/tetrate/users/dev-f
  - organizations/tetrate/users/mngr-def
  - organizations/tetrate/users/dev-u
  - organizations/tetrate/users/dev-v
  - organizations/tetrate/users/dev-w
  - organizations/tetrate/users/mngr-uvw
  - organizations/tetrate/users/dev-x
  - organizations/tetrate/users/dev-y
  - organizations/tetrate/users/dev-z
  - organizations/tetrate/users/mngr-xyz
