---
stages:
  - prereq
  - test
curl:
  artifacts:
    paths:
      - output
  needs:
    - prereq
  script:
    - ./test.sh curl
  stage: test
  when: manual
prereq:
  allow_failure: false
  artifacts:
    paths:
      - output
  cache:
    key: output
    paths:
      - output
  script:
    - ./prereq.sh check
  stage: prereq
  timeout: 30m
variables:
  TERM: xterm
  COUNT:
    description: "The number of curl calls"
    value: "20"
  TARGET:
    value: "cash1"
    options:
      - "cash1"
      - "cash2"
      - "comm1"
      - "comm2"
      - "invest1"
      - "invest2"
      - "private1"
      - "private2"
      - "retail1"
      - "retail2"
      - "wealth1"
      - "wealth2"
    description: "The traffic target. Set to any of the available applications."