---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: retailbank
  workspace: retail1
  name: tier1-retail1
spec:
  description: Tier1 Gateway Group for Application Retail1
  displayName: Tier1Retail1
  namespaceSelector:
    names:
      - "mgmt/tier1-gw-retail1"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: retailbank
  workspace: retail1
  name: ingress-retail1
spec:
  description: Ingress Gateway Group for Application Retail1
  displayName: IngressRetail1
  namespaceSelector:
    names:
      - "*/gateway-retail1"
  configMode: BRIDGED
