---
apiVersion: api.tsb.tetrate.io/v2
kind: User
metadata:
  name: john
  organization: tetrate
spec:
  displayName: John Doe
  email: john.doe@acme.com
  firstName: John
  lastName: Doe
  loginName: john
  sourceType: LOCAL
---
apiVersion: api.tsb.tetrate.io/v2
kind: User
metadata:
  name: bob
  organization: tetrate
spec:
  displayName: Bob Marley
  email: bob.marley@acme.com
  firstName: Bob
  lastName: Marley
  loginName: bob
  sourceType: LOCAL
---
apiVersion: api.tsb.tetrate.io/v2
kind: User
metadata:
  name: alice
  organization: tetrate
spec:
  displayName: Alice Wonderland
  email: alice.wonderland@acme.com
  firstName: Alice
  lastName: Wonderland
  loginName: alice
  sourceType: LOCAL
---
apiVersion: api.tsb.tetrate.io/v2
kind: User
metadata:
  name: dev-abc
  organization: tetrate
spec:
  displayName: Developer ABC
  email: dev-abc@acme.com
  firstName: Developer
  lastName: ABC
  loginName: dev-abc
  sourceType: LOCAL