---
apiVersion: v1
kind: Service
metadata:
  name: mid-comm2
  namespace: mid-comm2
  labels:
    app: mid-comm2
    service: mid-comm2
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 3000
      targetPort: 3000
      name: tcp
  selector:
    app: mid-comm2
