---
apiVersion: rbac.tsb.tetrate.io/v2
kind: Role
metadata:
  name: workspace-reader
spec:
  description: Read permissions on workspace resources
  displayName: WorkspaceReader
  rules:
  - permissions:
    - READ
    types:
    - apiGroup: api.tsb.tetrate.io/v2
      kinds:
      - Workspace
