---
apiVersion: v1
kind: Service
metadata:
  name: app-d
  namespace: ns-d
  labels:
    app: app-d
    service: app-d
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 3000
      targetPort: 3000
      name: tcp
  selector:
    app: app-d
