---
config-tsb:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - install-mp
    - install-cp
  resource_group: tctl
  script:
    - ./tsb.sh config
  stage: config-tsb
install-cp:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
    - install-mp
  resource_group: tctl
  script:
    - ./cp.sh install
  stage: install-cp
install-mp:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
  resource_group: tctl
  script:
    - ./mp.sh install
  stage: install-mp
prereq:
  allow_failure: false
  artifacts:
    paths:
      - output
  cache:
    key: output
    paths:
      - output
  script:
    - ./prereq.sh check
  stage: prereq
  timeout: 20m
stages:
  - prereq
  - install-mp
  - install-cp
  - config-tsb
variables:
  TERM: xterm