---
certs:
  artifacts:
    paths:
      - output/istio-certs
  cache:
    key: istio-certs
    paths:
      - output/istio-certs
  needs:
    - prereq
  script:
    - ./certs.sh generate
  stage: certs
config-tsb:
  artifacts:
    paths:
      - output/istio-certs
      - output/tsb
  environment:
    name: tctl
  needs:
    - install-mp
    - install-cp
  resource_group: tctl
  script:
    - ./tsb.sh config
  stage: config-tsb
install-cp:
  artifacts:
    paths:
      - output/istio-certs
      - output/tsb
  environment:
    name: tctl
  needs:
    - certs
    - install-mp
  resource_group: tctl
  script:
    - ./cp.sh install
  stage: install-cp
install-mp:
  artifacts:
    paths:
      - output/istio-certs
      - output/tsb
  environment:
    name: tctl
  needs:
    - certs
  resource_group: tctl
  script:
    - ./mp.sh install
  stage: install-mp
prereq:
  allow_failure: false
  script:
    - ./prereq.sh check
  stage: prereq
  timeout: 15m
stages:
  - prereq
  - certs
  - install-mp
  - install-cp
  - config-tsb
variables:
  TERM: xterm