---
apiVersion: v1
kind: Service
metadata:
  name: back-comm1
  namespace: back-comm1
  labels:
    app: back-comm1
    service: back-comm1
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 3000
      targetPort: 3000
      name: tcp
  selector:
    app: back-comm1
