---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  organization: tetrate
  tenant: commercialbank
  workspace: app-abc
  group: gwgroup-tier1-abc
  name: tier1-gw-abc
spec:
  description: Tier1 Gateway Group for Application ABC
  displayName: Tier1GwABC
  workloadSelector:
    namespace: tier1-gw-abc
    labels:
      app: tier1-gw-abc
  externalServers:
  - name: abc-mtls
    hostname: abc.demo.tetrate.io
    port: 443
    tls:
      mode: MUTUAL
      secretName: app-abc-cert
    clusters:
    - name: active
    - name: standby
