---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: commercialbank
  workspace: app-comm2
  name: app-comm2-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-comm2
        labels:
          app: eastwest-gw-comm2
      exposedServices:
      - serviceLabels:
          app: app-comm2a
          service: app-comm2a
      - serviceLabels:
          app: app-comm2b
          service: app-comm2b
      - serviceLabels:
          app: app-comm2c
          service: app-comm2c
  defaultTrafficSetting:
    reachability:
      hosts:
      - gateway-comm2/*
      - ns-comm2a/*
      - ns-comm2b/*
      - ns-comm2c/*
      mode: CUSTOM