---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: commercialbank
  workspace: comm2
  name: comm2-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-comm2
        labels:
          app: eastwest-gw-comm2
      exposedServices:
      - serviceLabels:
          app: frontend-comm2
          service: frontend-comm2
      - serviceLabels:
          app: middleware-comm2
          service: middleware-comm2
      - serviceLabels:
          app: backend-comm2
          service: backend-comm2
  defaultTrafficSetting:
    reachability:
      hosts:
      - gateway-comm2/*
      - frontend-comm2/*
      - middleware-comm2/*
      - backend-comm2/*
      mode: CUSTOM