---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: commercialbank
  workspace: comm1
  name: comm1-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-comm1
        labels:
          app: eastwest-gw-comm1
      exposedServices:
      - serviceLabels:
          app: frontend-comm1
          service: frontend-comm1
      - serviceLabels:
          app: middleware-comm1
          service: middleware-comm1
      - serviceLabels:
          app: backend-comm1
          service: backend-comm1
  defaultTrafficSetting:
    reachability:
      hosts:
      - gateway-comm1/*
      - frontend-comm1/*
      - middleware-comm1/*
      - backend-comm1/*
      mode: CUSTOM