---
apiVersion: api.tsb.tetrate.io/v2
kind: Team
metadata:
  organization: tetrate
  tenant: publicbanking
  name: team-abc
spec:
  members:
  - organizations/tetrate/users/dev-a
  - organizations/tetrate/users/dev-b
  - organizations/tetrate/users/dev-c
  - organizations/tetrate/users/mngr-abc
