---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: commercialbank
    tsb-workspace: app-comm2
  labels:
    istio-injection: enabled
  name: ns-comm2a
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: commercialbank
    tsb-workspace: app-comm2
  labels:
    istio-injection: enabled
  name: ns-comm2b
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: commercialbank
    tsb-workspace: app-comm2
  labels:
    istio-injection: enabled
  name: ns-comm2c
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: commercialbank
    tsb-workspace: app-comm2
  name: gateway-comm2
