---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  organization: tetrate
  tenant: investmentbank
  workspace: invest1
  group: ingress-invest1
  name: ingress-gw-invest1
spec:
  description: Ingress Gateway for Application Invest1
  displayName: IngressGwInvest1
  workloadSelector:
    namespace: gateway-invest1
    labels:
      app: ingress-gw-invest1
  http:
  - name: invest1-https
    hostname: invest1.demo.tetrate.io
    port: 443
    tls:
      mode: SIMPLE
      secretName: invest1-cert
    routing:
      rules:
      - route:
          host: front-invest1/front-invest1.front-invest1.svc.cluster.local
          port: 80
