---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: publicbanking
    tsb-workspace: app-abc
  labels:
    istio-injection: enabled
  name: ns-a
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: publicbanking
    tsb-workspace: app-abc
  labels:
    istio-injection: enabled
  name: ns-b
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: publicbanking
    tsb-workspace: app-abc
  labels:
    istio-injection: enabled
  name: ns-c
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: publicbanking
    tsb-workspace: app-abc
  name: gateway-abc
