stages:
  - mp
  - cp
variables:
  TERM: xterm
mp:
  artifacts:
    paths:
      - output/*
    exclude:
      - output/.gitignore
  stage: mp
  script:
    - ./mp.sh install
cp:
  artifacts:
    paths:
      - output/*
    exclude:
      - output/.gitignore
  needs:
    - mp
  stage: cp
  script:
    - ./cp.sh install

