stages:
  - certs
  - mp
  - cp
variables:
  TERM: xterm
certs:
  artifacts:
    paths:
      - output/istio-certs
  cache:
    key: istio-certs
    paths:
      - output/istio-certs
  stage: certs
  script:
    - ./certs.sh generate
mp:
  artifacts:
    paths:
      - output/istio-certs
      - output/tsb
  needs:
    - certs
  stage: mp
  script:
    - ./mp.sh install
cp:
  artifacts:
    paths:
      - output/istio-certs
      - output/tsb
  needs:
    - mp
  stage: cp
  script:
    - ./cp.sh install

