stages:
    - mp
    - cp

variables:
    TERM: "xterm" # Use Unix ASCII color codes on Nuke

mp:
    stage: mp
    script:
        - "./mp.sh install"

cp:
    needs: ["mp"]
    stage: cp
    script:
        - "./cp.sh install"
