---
certs:
  artifacts:
    paths:
      - output/istio-certs
  cache:
    key: istio-certs
    paths:
      - output/istio-certs
  needs:
    - artifacts: false
      job: sync
      project: tsb/images
      ref: main
    - artifacts: false
      job: up
      project: infra/minikube
      ref: main 
  script:
    - ./certs.sh generate
  stage: certs
config-tsb:
  artifacts:
    paths:
      - output/istio-certs
      - output/tsb
  needs:
    - install-mp
    - install-cp
  script:
    - ./tsb.sh config
  stage: config-tsb
install-cp:
  artifacts:
    paths:
      - output/istio-certs
      - output/tsb
  needs:
    - certs
    - install-mp
  script:
    - ./cp.sh install
  stage: install-cp
install-mp:
  artifacts:
    paths:
      - output/istio-certs
      - output/tsb
  needs:
    - certs
  script:
    - ./mp.sh install
  stage: install-mp
stages:
  - certs
  - install-mp
  - install-cp
  - config-tsb
variables:
  TERM: xterm