stages:
  - certs
  - install-mp
  - install-cp
  - config-tsb
variables:
  TERM: xterm
certs:
  artifacts:
    paths:
      - output/istio-certs
  cache:
    key: istio-certs
    paths:
      - output/istio-certs
  # needs:
  #   - job: sync
  #     pipeline: tsb/images
  #   - job: up
  #     pipeline: infra/minikube
  stage: certs
  script:
    - ./certs.sh generate
install-mp:
  artifacts:
    paths:
      - output/istio-certs
      - output/tsb
  needs:
    - certs
  stage: install-mp
  script:
    - ./mp.sh install
install-cp:
  artifacts:
    paths:
      - output/istio-certs
      - output/tsb
  needs:
    - certs
    - install-mp
  stage: install-cp
  script:
    - ./cp.sh install
config-tsb:
  artifacts:
    paths:
      - output/istio-certs
      - output/tsb
  needs:
    - install-mp
    - install-cp
  stage: config-tsb
  script:
    - ./tsb.sh config

