---
apiVersion: api.tsb.tetrate.io/v2
kind: Organization
metadata:
  name: tetrate
---
apiVersion: api.tsb.tetrate.io/v2
kind: OrganizationSetting
metadata:
  name: tetrate-settings
  organization: tetrate
spec:
  defaultSecuritySetting: {}
  defaultTrafficSetting: {}
  networkSettings:
    networkReachability:
      tier1: tier2
  regionalFailover: {}