---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: retailbank
    tsb-workspace: retail2
  labels:
    istio-injection: enabled
  name: ns-retail2a
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: retailbank
    tsb-workspace: retail2
  labels:
    istio-injection: enabled
  name: ns-retail2b
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: retailbank
    tsb-workspace: retail2
  labels:
    istio-injection: enabled
  name: ns-retail2c
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: retailbank
    tsb-workspace: retail2
  name: gateway-retail2
