---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: retailbank
    tsb-workspace: retail1
  labels:
    istio-injection: enabled
  name: front-retail
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: retailbank
    tsb-workspace: retail1
  labels:
    istio-injection: enabled
  name: mid-retail
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: retailbank
    tsb-workspace: retail1
  labels:
    istio-injection: enabled
  name: back-retail
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb-tenant: retailbank
    tsb-workspace: retail1
  name: gateway-retail1
