---
apiVersion: v1
kind: Service
metadata:
  name: front-invest1
  namespace: front-invest1
  labels:
    app: front-invest1
    service: front-invest1
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 3000
      targetPort: 3000
      name: tcp
  selector:
    app: front-invest1
