---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private2
  name: tier1-private2
spec:
  description: Tier1 Gateway Group for Application Private2
  displayName: Tier1Private2
  namespaceSelector:
    names:
      - "mgmt/tier1-gw-private2"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private2
  name: ingress-private2
spec:
  description: Ingress Gateway Group for Application Private2
  displayName: IngressPrivate2
  namespaceSelector:
    names:
      - "*/gateway-private2"
  configMode: BRIDGED
