---
apiVersion: api.tsb.tetrate.io/v2
kind: ServiceAccount
metadata:
  name: cashmgmt
  organization: tetrate
spec:
  displayName: CashMgmtSA
  description: ServiceAccount used for CICD driven TSB Management of Tenant CashMgmt
