---
apiVersion: api.tsb.tetrate.io/v2
kind: ServiceAccount
metadata:
  name: commercialbank
  organization: tetrate
spec:
  displayName: CommercialBankSA
  description: ServiceAccount used for CICD driven TSB Management of Tenant CommercialBank
