---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: publicbanking
  workspace: app-abc
  group: secgroup-ingress-abc
  name: tier1-to-ingress
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-abc/securitygroups/secgroup-tier1-abc
         to:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-abc/securitygroups/secgroup-ingress-abc
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: publicbanking
  workspace: app-abc
  group: secgroup-a
  name: ingress-to-a
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-abc/securitygroups/secgroup-ingress-abc
         to:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-abc/securitygroups/secgroup-a
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: publicbanking
  workspace: app-abc
  group: secgroup-b
  name: a-to-b
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-abc/securitygroups/secgroup-a
         to:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-abc/securitygroups/secgroup-b
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: publicbanking
  workspace: app-abc
  group: secgroup-c
  name: b-to-c
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-abc/securitygroups/secgroup-b
         to:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-abc/securitygroups/secgroup-c
