---
apiVersion: api.tsb.tetrate.io/v2
kind: ServiceAccount
metadata:
  name: sa-uvw
  organization: tetrate
spec:
  displayName: AppUVW_SA
  description: ServiceAccount used for CICD driven TSB Management of AppUVW
