---
apiVersion: rbac.tsb.tetrate.io/v2
kind: Role
metadata:
  name: user-reader
spec:
  displayName: UserReader
  rules:
  - permissions:
    - READ
    types:
    - apiGroup: api.tsb.tetrate.io/v2
      kinds:
      - Team
      - User