---
gen-certs:
  artifacts:
    paths:
      - output
  cache:
    key: certificates
    paths:
      - output
  script:
    - ./certs.sh generate
  stage: gen-certs
  tags:
    - platform-infra
stages:
  - gen-certs
variables:
  TERM: xterm