---
deploy-all:
  script: echo "going to deploy all applications"
  stage: all
  when: manual
deploy-privatebank:
  needs:
    - deploy-all
  script: echo "going to deploy all privatebank applications"
  stage: single-tenant
deploy-private1:
  needs:
    - deploy-privatebank
  script: echo "going to deploy the private1 application"
  stage: single-application
deploy-private1-frontend:
  needs:
    - deploy-private1
  stage: single-microservice
  trigger:
    project: applications/privatebank/private1/frontend-private1
deploy-private1-middleware:
  needs:
    - deploy-private1
  stage: single-microservice
  trigger:
    project: applications/privatebank/private1/middleware-private1
deploy-private1-backend:
  needs:
    - deploy-private1
  stage: single-microservice
  trigger:
    project: applications/privatebank/private1/backend-private1
deploy-private2:
  needs:
    - deploy-privatebank
  script: echo "going to deploy the private2 application"
  stage: single-application
deploy-private2-frontend:
  needs:
    - deploy-private2
  stage: single-microservice
  trigger:
    project: applications/privatebank/private2/frontend-private2
deploy-private2-middleware:
  needs:
    - deploy-private2
  stage: single-microservice
  trigger:
    project: applications/privatebank/private2/middleware-private2
deploy-private2-backend:
  needs:
    - deploy-private2
  stage: single-microservice
  trigger:
    project: applications/privatebank/private2/backend-private2
deploy-retailbank:
  needs:
    - deploy-all
  script: echo "going to deploy all retailbank applications"
  stage: single-tenant
deploy-retail1:
  needs:
    - deploy-retailbank
  script: echo "going to deploy the retail1 application"
  stage: single-application
deploy-retail1-frontend:
  needs:
    - deploy-retail1
  stage: single-microservice
  trigger:
    project: applications/retailbank/retail1/frontend-retail1
deploy-retail1-middleware:
  needs:
    - deploy-retail1
  stage: single-microservice
  trigger:
    project: applications/retailbank/retail1/middleware-retail1
deploy-retail1-backend:
  needs:
    - deploy-retail1
  stage: single-microservice
  trigger:
    project: applications/retailbank/retail1/backend-retail1
deploy-retail2:
  needs:
    - deploy-retailbank
  script: echo "going to deploy the retail2 application"
  stage: single-application
deploy-retail2-frontend:
  needs:
    - deploy-retail2
  stage: single-microservice
  trigger:
    project: applications/retailbank/retail2/frontend-retail2
deploy-retail2-middleware:
  needs:
    - deploy-retail2
  stage: single-microservice
  trigger:
    project: applications/retailbank/retail2/middleware-retail2
deploy-retail2-backend:
  needs:
    - deploy-retail2
  stage: single-microservice
  trigger:
    project: applications/retailbank/retail2/backend-retail2
stages:
  - all
  - single-tenant
  - single-application
  - single-microservice
variables:
  TERM: xterm