---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/retailbank/workspaces/retail2
  labels:
    istio-injection: enabled
  name: front-retail2
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/retailbank/workspaces/retail2
  labels:
    istio-injection: enabled
  name: mid-retail2
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/retailbank/workspaces/retail2
  labels:
    istio-injection: enabled
  name: back-retail2
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/retailbank/workspaces/retail2
  name: gateway-retail2
