---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: publicbanking
  workspace: app-def
  name: app-def-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-def
        labels:
          app: eastwest-gw-def
      exposedServices:
      - serviceLabels:
          app: app-d
          service: app-d
      - serviceLabels:
          app: app-e
          service: app-e
      - serviceLabels:
          app: app-f
          service: app-f
  defaultTrafficSetting:
    reachability:
      hosts:
      - gateway-def/*
      - ns-d/*
      - ns-e/*
      - ns-f/*
      mode: CUSTOM