---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: publicbanking
  workspace: app-def
  name: app-def-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-def
        labels:
          app: gw-eastwest-def
      exposedServices:
      - serviceLabels:
          app: svc-d
          service: svc-d
      - serviceLabels:
          app: svc-e
          service: svc-e
      - serviceLabels:
          app: svc-f
          service: svc-f
  defaultTrafficSetting:
    reachability:
      hosts:
      - gateway-def/*
      - ns-d/*
      - ns-e/*
      - ns-f/*
      mode: CUSTOM