---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: commercialbank
  workspace: comm1
  group: ingress-comm1
  name: tier1-to-ingress
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/commercialbank/workspaces/comm1/securitygroups/tier1-comm1
         to:
           fqn: organizations/tetrate/tenants/commercialbank/workspaces/comm1/securitygroups/ingress-comm1
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: commercialbank
  workspace: comm1
  group: front-comm1
  name: ingress-to-front
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/commercialbank/workspaces/comm1/securitygroups/ingress-comm1
         to:
           fqn: organizations/tetrate/tenants/commercialbank/workspaces/comm1/securitygroups/front-comm1
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: commercialbank
  workspace: comm1
  group: mid-comm1
  name: front-to-mid
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/commercialbank/workspaces/comm1/securitygroups/front-comm1
         to:
           fqn: organizations/tetrate/tenants/commercialbank/workspaces/comm1/securitygroups/mid-comm1
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: commercialbank
  workspace: comm1
  group: back-comm1
  name: mid-to-back
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/commercialbank/workspaces/comm1/securitygroups/mid-comm1
         to:
           fqn: organizations/tetrate/tenants/commercialbank/workspaces/comm1/securitygroups/back-comm1
