---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: people-ldif
  namespace: tsb
data:
  02-people.ldif: |
    ############
    ## People ##
    ############

    dn: cn=Zack Butcher,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Zack Butcher
    givenname: Zack
    sn: Butcher
    uid: zack
    mail: zack@tetrate.io
    userpassword: zack

    dn: cn=Ignasi Barrera,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Ignasi Barrera
    givenname: Ignasi
    sn: Barrera
    uid: nacx
    mail: ignasi@tetrate.io
    userpassword: nacx

    dn: cn=Wu Sheng,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Wu Sheng
    givenname: Wu
    sn: Sheng
    uid: wusheng
    mail: wusheng@tetrate.io
    userpassword: wusheng

    dn: cn=Bart Van Bos,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Bart Van Bos
    givenname: Bart
    sn: Van Bos
    uid: bart
    mail: bart@tetrate.io
    userpassword: bart

    #################################### platform managers ####################################

    dn: cn=Manager TsbPlatform,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Manager TsbPlatform
    givenname: Manager
    sn: TsbPlatformMngr
    uid: mngr-tsb-platform
    mail: mngr-tsb-platform@tetrate.io
    userpassword: mngr-tsb-platform

    #################################### tenant/bu managers ####################################

    dn: cn=Manager PrivateBank,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Manager PrivateBank
    givenname: Manager
    sn: PrivateBank
    uid: mngr-privatebank
    mail: mngr-privatebank@tetrate.io
    userpassword: mngr-privatebank

    dn: cn=Manager RetailBank,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Manager RetailBank
    givenname: Manager
    sn: RetailBank
    uid: mngr-retailbank
    mail: mngr-retailbank@tetrate.io
    userpassword: mngr-retailbank

    #################################### application/workspace teamleads ####################################

    dn: cn=TeamLead Private1,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: TeamLead Private1
    givenname: TeamLead
    sn: Private1
    uid: tl-private1
    mail: tl-private1@tetrate.io
    userpassword: tl-private1
    
    dn: cn=TeamLead Private2,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: TeamLead Private2
    givenname: TeamLead
    sn: Private2
    uid: tl-private2
    mail: tl-private2@tetrate.io
    userpassword: tl-private2
    
    dn: cn=TeamLead Retail1,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: TeamLead Retail1
    givenname: TeamLead
    sn: Retail1
    uid: tl-retail1
    mail: tl-retail1@tetrate.io
    userpassword: tl-retail1
    
    dn: cn=TeamLead Retail2,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: TeamLead Retail2
    givenname: TeamLead
    sn: Retail2
    uid: tl-retail2
    mail: tl-retail2@tetrate.io
    userpassword: tl-retail2

    #################################### full-stack developers ####################################

    dn: cn=Developer Private1,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Private1
    givenname: Developer
    sn: Private1
    uid: dev-private1
    mail: dev-private1@tetrate.io
    userpassword: dev-private1

    dn: cn=Developer Private2,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Private2
    givenname: Developer
    sn: Private2
    uid: dev-private2
    mail: dev-private2@tetrate.io
    userpassword: dev-private2

    dn: cn=Developer Retail1,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Retail1
    givenname: Developer
    sn: Retail1
    uid: dev-retail1
    mail: dev-retail1@tetrate.io
    userpassword: dev-retail1

    dn: cn=Developer Retail2,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Retail2
    givenname: Developer
    sn: Retail2
    uid: dev-retail2
    mail: dev-retail2@tetrate.io
    userpassword: dev-retail2

    #################################### frontend developers ####################################

    dn: cn=Developer Private1 Frontend,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Private1 Frontend
    givenname: Developer
    sn: Private1 Frontend
    uid: dev-private1-frontend
    mail: dev-private1-frontend@tetrate.io
    userpassword: dev-private1-frontend

    dn: cn=Developer Private2 Frontend,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Private2 Frontend
    givenname: Developer
    sn: Private2 Frontend
    uid: dev-private2-frontend
    mail: dev-private2-frontend@tetrate.io
    userpassword: dev-private2-frontend

    dn: cn=Developer Retail1 Frontend,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Retail1 Frontend
    givenname: Developer
    sn: Retail1 Frontend
    uid: dev-retail1-frontend
    mail: dev-retail1-frontend@tetrate.io
    userpassword: dev-retail1-frontend

    dn: cn=Developer Retail2 Frontend,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Retail2 Frontend
    givenname: Developer
    sn: Retail2 Frontend
    uid: dev-retail2-frontend
    mail: dev-retail2-frontend@tetrate.io
    userpassword: dev-retail2-frontend

    #################################### middleware developers ####################################

    dn: cn=Developer Private1 Middleware,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Private1 Middleware
    givenname: Developer
    sn: Private1 Middleware
    uid: dev-private1-middleware
    mail: dev-private1-middleware@tetrate.io
    userpassword: dev-private1-middleware

    dn: cn=Developer Private2 Middleware,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Private2 Middleware
    givenname: Developer
    sn: Private2 Middleware
    uid: dev-private2-middleware
    mail: dev-private2-middleware@tetrate.io
    userpassword: dev-private2-middleware

    dn: cn=Developer Retail1 Middleware,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Retail1 Middleware
    givenname: Developer
    sn: Retail1 Middleware
    uid: dev-retail1-middleware
    mail: dev-retail1-middleware@tetrate.io
    userpassword: dev-retail1-middleware

    dn: cn=Developer Retail2 Middleware,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Retail2 Middleware
    givenname: Developer
    sn: Retail2 Middleware
    uid: dev-retail2-middleware
    mail: dev-retail2-middleware@tetrate.io
    userpassword: dev-retail2-middleware

    #################################### backend developers ####################################

    dn: cn=Developer Private1 Backend,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Private1 Backend
    givenname: Developer
    sn: Private1 Backend
    uid: dev-private1-backend
    mail: dev-private1-backend@tetrate.io
    userpassword: dev-private1-backend

    dn: cn=Developer Private2 Backend,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Private2 Backend
    givenname: Developer
    sn: Private2 Backend
    uid: dev-private2-backend
    mail: dev-private2-backend@tetrate.io
    userpassword: dev-private2-backend

    dn: cn=Developer Retail1 Backend,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Retail1 Backend
    givenname: Developer
    sn: Retail1 Backend
    uid: dev-retail1-backend
    mail: dev-retail1-backend@tetrate.io
    userpassword: dev-retail1-backend

    dn: cn=Developer Retail2 Backend,ou=People,dc=tetrate,dc=io
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    objectclass: top
    cn: Developer Retail2 Backend
    givenname: Developer
    sn: Retail2 Backend
    uid: dev-retail2-backend
    mail: dev-retail2-backend@tetrate.io
    userpassword: dev-retail2-backend
