---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: app-xyz
  group: gwgroup-ingress-xyz
  name: ingress-gw-xyz
spec:
  description: Ingress Gateway for Application XYZ
  displayName: IngressGwXYZ
  workloadSelector:
    namespace: gateway-xyz
    labels:
      app: ingress-gw-xyz
  http:
  - name: xyz
    hostname: xyz.demo.tetrate.io
    port: 443
    tls:
      mode: SIMPLE
      secretName: app-xyz-cert
    routing:
      rules:
      - route:
          host: ns-x/app-x.ns-x.svc.cluster.local
          port: 80
