---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private2
  group: ingress-private2
  name: ingress-gw-private2
spec:
  description: Ingress Gateway for Application Private2
  displayName: IngressGwPrivate2
  workloadSelector:
    namespace: gateway-private2
    labels:
      app: ingress-gw-private2
  http:
  - name: private2-https
    hostname: private2.demo.tetrate.io
    port: 443
    tls:
      mode: SIMPLE
      secretName: private2-cert
    routing:
      rules:
      - route:
          host: front-private2/front-private2.front-private2.svc.cluster.local
          port: 80
