---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private2
  group: ingress-private2
  name: tier1-to-ingress
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private2/securitygroups/tier1-private2
         to:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private2/securitygroups/ingress-private2
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private2
  group: front-private2
  name: ingress-to-front
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private2/securitygroups/ingress-private2
         to:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private2/securitygroups/front-private2
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private2
  group: mid-private2
  name: front-to-mid
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private2/securitygroups/front-private2
         to:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private2/securitygroups/mid-private2
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private2
  group: back-private2
  name: mid-to-back
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private2/securitygroups/mid-private2
         to:
           fqn: organizations/tetrate/tenants/privatebank/workspaces/private2/securitygroups/back-private2
