---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  organization: tetrate
  tenant: privatebank
  workspace: private2
  group: tier1-private2
  name: tier1-gw-private2
spec:
  description: Tier1 Gateway Group for Application Private2
  displayName: Tier1GwPrivate2
  workloadSelector:
    namespace: tier1-gw-private2
    labels:
      app: tier1-gw-private2
  externalServers:
  - name: private2-mtls
    hostname: private2.demo.tetrate.io
    port: 443
    tls:
      mode: MUTUAL
      secretName: private2-cert
    clusters:
    - name: active
    - name: standby
