---
apiVersion: rbac.tsb.tetrate.io/v2
kind: Role
metadata:
  name: cluster-reader
spec:
  displayName: ClusterReader
  rules:
  - permissions:
    - READ
    types:
    - apiGroup: api.tsb.tetrate.io/v2
      kinds:
      - Cluster
      - Organization