---
privatebank-tenant:
  needs:
    - tetrate-organization
  stage: post-trigger
  trigger:
    project: applications/privatebank/tsb-tenant-admin
retailbank-tenant:
  needs:
    - tetrate-organization
  stage: post-trigger
  trigger:
    project: applications/retailbank/tsb-tenant-admin
prereq:
  allow_failure: false
  script:
    - ./prereq.sh check
  stage: prereq
  tags:
    - platform-tsb
  timeout: 30m
stages:
  - prereq
  - tsb-deploy
  - post-trigger
tetrate-organization:
  artifacts:
    paths:
      - output
  environment:
    name: tctl
  needs:
    - prereq
  resource_group: tctl
  script:
    - ./tsb.sh deploy
  stage: tsb-deploy
  tags:
    - platform-tsb
variables:
  TERM: xterm