---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  organization: tetrate
  tenant: publicbanking
  workspace: app-def
  group: gwgroup-tier1-def
  name: tier1-gw-def
spec:
  description: Tier1 Gateway Group for Application DEF
  displayName: Tier1GwDEF
  workloadSelector:
    namespace: tier1-gw-def
    labels:
      app: tier1-gw-def
  externalServers:
  - name: def-mtls
    hostname: def.demo.tetrate.io
    port: 443
    tls:
      mode: MUTUAL
      secretName: app-def-cert
    clusters:
    - name: active
    - name: standby
