---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: cashmgmt
  workspace: cash2
  name: cash2
spec:
  description: Traffic Group for Application Cash2
  displayName: Cash2
  namespaceSelector:
    names:
      - "*/front-cash2"
      - "*/mid-cash2"
      - "*/back-cash2"
  configMode: BRIDGED
